### ISSUE TITLE
Correct missing Pics/Logos

### ISSUE THREAD

**Issue by Triandafilidis** [ahk-ch/chamb.net#17]
https://chamb.net/companies

Implement missing Site pics
Implement missing Company Logos 

Correct missing transition from community site to company Profile. 
(there is no connection to company profile when a user "clicks" on a specific company)

**Comment by rdok** [comment]
@Triandafilidis 
- All site pics are already implemented on this url.
- All company logos are already implanted on the provided url. They are just dummy pics with text log.
- All transition mentioned are already implemented. (click either on the description or the logo). Note: only the blue tags for industries are missing, since we do not have constructed page showing companies with specific industry.
